import { Card, CardActionArea, CardContent, Stack, Tooltip, Typography } from '@mui/material'
import { ArtifactListItemReducedDTO } from '../../../../../autogenerated/client/backend'
import { Link, useNavigate } from 'react-router-dom'
import moment from 'moment'
import { Adjust, LayersOutlined, SyncOutlined } from '@mui/icons-material'
import GitBranch from '../../../../components/GitBranch/GitBranch'
import InstallDialog from '../InstallDialog'
import { useState } from 'react'
import Grid from '@mui/material/Unstable_Grid2'

export default function BranchCard({ branch, version, artifact }: 
{ branch: { name: string, pattern: string }, version: string, artifact: ArtifactListItemReducedDTO }) {
  const [ installDialogOpen, setInstallDialogOpen ] = useState<boolean>(false)

  const navigate = useNavigate()

  return (
    <Grid 
      xs={ 12 }
      md={ 12 }
      lg={ 6 }>
      <Card 
        variant='outlined' 
        sx={ { 
          maxWidth: 'lg', 
          '&:hover': { borderColor: 'primary.main', boxShadow: 2 } } }>
        <CardActionArea 
          onClick={ () => setInstallDialogOpen(true) }>
          <CardContent>
            <Stack
              direction='row'
              justifyContent='space-between'>
              <Stack
                direction='column'
                alignItems='start'
                spacing={ 1 }>
                <Typography variant='h4'>Version { version }</Typography>
                <Stack
                  direction='row'
                  justifyContent='start'
                  alignItems='center'
                  spacing={ 2 }>
                  <Tooltip
                    title='Branch'
                    PopperProps={ {
                      modifiers: [
                        {
                          name: 'offset',
                          options: {
                            offset: [0, -4]
                          }
                        }
                      ]
                    } }>
                    <Stack 
                      direction='row'
                      justifyContent='start'
                      alignItems='center'
                      spacing={ 0.5 }>
                      <GitBranch 
                        fontSize='small'
                        sx={ { color: 'text.secondary' } } />
                      <Typography 
                        color='text.secondary'>
                        { branch.name }
                      </Typography>
                    </Stack>
                  </Tooltip>
                  <Tooltip
                    title='Chart version'
                    PopperProps={ {
                      modifiers: [
                        {
                          name: 'offset',
                          options: {
                            offset: [0, -4]
                          }
                        }
                      ]
                    } }>
                    <Stack 
                      direction='row'
                      justifyContent='start'
                      alignItems='center'
                      spacing={ 0.5 }>
                      <LayersOutlined 
                        fontSize='small'
                        sx={ { color: 'text.secondary' } } />
                      <Typography 
                        color='text.secondary'>
                        { artifact.version }-{ artifact.revision }
                      </Typography>
                    </Stack>
                  </Tooltip>
                  <Tooltip
                    title='Last updated'
                    PopperProps={ {
                      modifiers: [
                        {
                          name: 'offset',
                          options: {
                            offset: [0, -4]
                          }
                        }
                      ]
                    } }>
                    <Stack
                      direction='row'
                      justifyContent='start'
                      alignItems='center'
                      spacing={ 0.5 }>
                      <SyncOutlined 
                        fontSize='small'
                        sx={ { color: 'text.secondary' } } />
                      <Typography 
                        color='text.secondary'>
                        { moment(artifact.registered_at).fromNow() }
                      </Typography>
                    </Stack>
                  </Tooltip>
                  <Tooltip
                    title='Short digest'
                    PopperProps={ {
                      modifiers: [
                        {
                          name: 'offset',
                          options: {
                            offset: [0, -4]
                          }
                        }
                      ]
                    } }>
                    <Stack
                      direction='row'
                      justifyContent='start'
                      alignItems='center'
                      spacing={ 0.5 }>
                      <Adjust 
                        fontSize='small'
                        sx={ { color: 'text.secondary' } } />
                      <Typography 
                        color='text.secondary'>
                        { artifact?.digest.value.substring(0, 7) }
                      </Typography>
                    </Stack>
                  </Tooltip>
                </Stack>
              </Stack>
            </Stack>
          </CardContent>
        </CardActionArea>
      </Card>
      <InstallDialog 
        branch={ branch.name }
        artifact={ artifact }
        version={ version }
        isOpen={ installDialogOpen }
        onSubmit={ (result) => {
          setInstallDialogOpen(false)
          navigate('/workloads')
        } }
        onDismiss={ () => setInstallDialogOpen(false) }/>
    </Grid>
  )
}