import { Card, CardActionArea, CardContent, Skeleton, Stack, Typography } from '@mui/material'
import { ArtifactListItemReducedDTO } from '../../../../../autogenerated/client/backend'
import { useNavigate } from 'react-router-dom'
import moment from 'moment'
import { AdjustOutlined, LayersOutlined, SvgIconComponent, SyncOutlined } from '@mui/icons-material'
import GitBranch from '../../../../components/GitBranch/GitBranch'
import InstallDialog from '../InstallDialog'
import { useState } from 'react'
import HintIcon, { LoadingHintIcon } from './HintIcon'

export default function BranchCard({ branch, version, artifact }: 
{ branch: { name: string, pattern: string }, version: string, artifact: ArtifactListItemReducedDTO }) {
  const [ installDialogOpen, setInstallDialogOpen ] = useState<boolean>(false)

  const navigate = useNavigate()

  function onInstall() {
    setInstallDialogOpen(false)
    navigate('/workloads')
  }

  return (
    <>
      <Card 
        variant='outlined' 
        sx={ { 
          maxWidth: 'lg', 
          '&:hover': { borderColor: 'primary.main', boxShadow: 2 } 
        } }>
        <CardActionArea onClick={ () => setInstallDialogOpen(true) }>
          <CardContent>
            <Stack direction='row' justifyContent='space-between'>
              <Stack direction='column' alignItems='start' spacing={ 1 }>
                <Typography variant='h4'>Version { version }</Typography>
                <Stack direction='row' justifyContent='start' alignItems='center' spacing={ 2 }>
                  <HintIcon tooltip='Branch' icon={ GitBranch as SvgIconComponent } text={ branch.name } />
                  <HintIcon tooltip='Chart version' icon={ LayersOutlined } text={ `${ artifact.version }-${ artifact.revision }` } />
                  <HintIcon tooltip='Last updated' icon={ SyncOutlined } text={ moment(artifact.registered_at).fromNow() } />
                  <HintIcon tooltip='Short digest' icon={ AdjustOutlined } text={ artifact?.digest.value.substring(0, 7) } />
                </Stack>
              </Stack>
            </Stack>
          </CardContent>
        </CardActionArea>
      </Card>
      <InstallDialog 
        branch={ branch.name } 
        artifact={ artifact } 
        version={ version } 
        isOpen={ installDialogOpen } 
        onSubmit={ onInstall } 
        onDismiss={ () => setInstallDialogOpen(false) }/>
    </>
  )
}

export function LoadingBranchCard() {
  return (
    <Card variant='outlined' sx={ { maxWidth: 'lg' } }>
      <CardActionArea disabled>
        <CardContent>
          <Stack direction='row' justifyContent='space-between'>
            <Stack direction='column' alignItems='start' spacing={ 1 }>
              <Skeleton variant='text' height={ 24 } width={ 97 }/>
              <Stack direction='row' justifyContent='start' alignItems='center' spacing={ 2 }>
                <LoadingHintIcon width={ 39 }/>
                <LoadingHintIcon width={ 73 }/>
                <LoadingHintIcon width={ 107 }/>
                <LoadingHintIcon width={ 74 }/>
              </Stack>
            </Stack>
          </Stack>
        </CardContent>
      </CardActionArea>
    </Card>
  )
}