FROM registry.suse.com/bci/bci-base:15.6 AS fetcher

ARG TARGETARCH
ENV BINS_DIR=/tmp/binaries/darwin
ENV HELM_VERSION=3.17.3
ENV HELM_MACOS_AMD64_CHECKSUM=20ef8df4671349a6fc556a621be1170dd709c6c0cf5f7e83a2d9fb0515fd97fc
ENV HELM_MACOS_ARM64_CHECKSUM=89aec43ce07b06239f1bba4a6507236bb48ae487bc5065a8e254d3ce58a16997
ENV HELM_LINUX_AMD64_CHECKSUM=ee88b3c851ae6466a3de507f7be73fe94d54cbf2987cbaa3d1a3832ea331f2cd
ENV HELM_LINUX_ARM64_CHECKSUM=7944e3defd386c76fd92d9e6fec5c2d65a323f6fadc19bfb5e704e3eee10348e
ENV HELM_WINDOWS_AMD64_CHECKSUM=8ea93e2f6285e649dede583ac90ff8cdb938ca53ec6cf5fe909f2303fbc22d96
ENV HELM_WINDOWS_ARM64_CHECKSUM=70ce9dfdbc1ce6142626a829dbdc5920405146f3ce4dc6f6e6739dd308cc7baf
ENV KUBECTL_VERSION=1.33.0
ENV KUBECTL_MACOS_AMD64_CHECKSUM=950850b17ba710101d1a403d126a5689556814c53c4c6f4c2b0224652add84b6
ENV KUBECTL_MACOS_ARM64_CHECKSUM=007746617abc12746dd80ad6c261c2b062269688d44c0b97aa47108c562b07c1
ENV KUBECTL_LINUX_AMD64_CHECKSUM=9efe8d3facb23e1618cba36fb1c4e15ac9dc3ed5a2c2e18109e4a66b2bac12dc
ENV KUBECTL_LINUX_ARM64_CHECKSUM=48541d119455ac5bcc5043275ccda792371e0b112483aa0b29378439cf6322b9
ENV KUBECTL_WINDOWS_AMD64_CHECKSUM=db6d96f65a86426e6c9484ca88a233aa7f160025f40c20b153c5bf4f9746c791
ENV KUBECTL_WINDOWS_ARM64_CHECKSUM=90a2b6eb214c895381cc63b5fd8653fa6a89cc4afc7c732ff726fe3a56ff86b4

RUN mkdir -p ${BINS_DIR}
RUN HELM_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && HELM_CHECKSUM_VAR="HELM_MACOS_${HELM_ARCH_UPPER}_CHECKSUM" \
    && HELM_CHECKSUM=$(printenv "${HELM_CHECKSUM_VAR}") \
    && KUBECTL_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && KUBECTL_CHECKSUM_VAR="KUBECTL_MACOS_${KUBECTL_ARCH_UPPER}_CHECKSUM" \
    && KUBECTL_CHECKSUM=$(printenv "${KUBECTL_CHECKSUM_VAR}") \
    && curl -s -o helm-v${HELM_VERSION}-darwin-${TARGETARCH}.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-darwin-${TARGETARCH}.tar.gz \
    && echo "${HELM_CHECKSUM}  helm-v${HELM_VERSION}-darwin-${TARGETARCH}.tar.gz" | sha256sum -c - \
    && tar -zxvf helm-v${HELM_VERSION}-darwin-${TARGETARCH}.tar.gz \
    && mv darwin-${TARGETARCH}/helm ${BINS_DIR}/helm \
    && curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/darwin/${TARGETARCH}/kubectl" \
    && echo "${KUBECTL_CHECKSUM}  kubectl" | sha256sum -c - \
    && chmod +x ./kubectl \
    && mv kubectl ${BINS_DIR}/kubectl

ENV BINS_DIR=/tmp/binaries/linux
RUN mkdir -p ${BINS_DIR}
RUN HELM_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && HELM_CHECKSUM_VAR="HELM_LINUX_${HELM_ARCH_UPPER}_CHECKSUM" \
    && HELM_CHECKSUM=$(printenv "${HELM_CHECKSUM_VAR}") \
    && KUBECTL_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && KUBECTL_CHECKSUM_VAR="KUBECTL_LINUX_${KUBECTL_ARCH_UPPER}_CHECKSUM" \
    && KUBECTL_CHECKSUM=$(printenv "${KUBECTL_CHECKSUM_VAR}") \
    && curl -s -o helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz \
    && echo "${HELM_CHECKSUM}  helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" | sha256sum -c - \
    && tar -zxvf helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz \
    && mv linux-${TARGETARCH}/helm ${BINS_DIR}/helm \
    && curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl" \
    && echo "${KUBECTL_CHECKSUM}  kubectl" | sha256sum -c - \
    && chmod +x ./kubectl \
    && mv kubectl ${BINS_DIR}/kubectl

ENV BINS_DIR=/tmp/binaries/windows
RUN mkdir -p ${BINS_DIR}
RUN HELM_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && HELM_CHECKSUM_VAR="HELM_WINDOWS_${HELM_ARCH_UPPER}_CHECKSUM" \
    && HELM_CHECKSUM=$(printenv "${HELM_CHECKSUM_VAR}") \
    && KUBECTL_ARCH_UPPER=$(echo "${TARGETARCH}" | tr '[:lower:]' '[:upper:]') \
    && KUBECTL_CHECKSUM_VAR="KUBECTL_WINDOWS_${KUBECTL_ARCH_UPPER}_CHECKSUM" \
    && KUBECTL_CHECKSUM=$(printenv "${KUBECTL_CHECKSUM_VAR}") \
    && curl -s -o helm-v${HELM_VERSION}-windows-${TARGETARCH}.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-windows-${TARGETARCH}.tar.gz \
    && echo "${HELM_CHECKSUM}  helm-v${HELM_VERSION}-windows-${TARGETARCH}.tar.gz" | sha256sum -c - \
    && tar -zxvf helm-v${HELM_VERSION}-windows-${TARGETARCH}.tar.gz \
    && mv windows-${TARGETARCH}/helm.exe ${BINS_DIR}/helm.exe \
    && curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/windows/${TARGETARCH}/kubectl.exe" \
    && echo "${KUBECTL_CHECKSUM}  kubectl.exe" | sha256sum -c - \
    && mv kubectl.exe ${BINS_DIR}/kubectl.exe

FROM --platform=$BUILDPLATFORM openapitools/openapi-generator-cli:v7.14.0 AS backend-client-generator

COPY ui /ui
WORKDIR /ui

RUN /usr/local/bin/docker-entrypoint.sh generate -g typescript-axios -i https://api.apps.rancher.io/api-docs -o autogenerated/client/backend --model-name-suffix=DTO

FROM --platform=$BUILDPLATFORM dp.apps.rancher.io/containers/nodejs:24-dev AS client-builder
WORKDIR /ui
# cache packages in layer
COPY ui/package.json /ui/package.json
COPY ui/package-lock.json /ui/package-lock.json
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci
# install
COPY ui /ui
COPY --from=backend-client-generator /ui/autogenerated /ui/autogenerated
RUN npm run build

FROM --platform=$BUILDPLATFORM dp.apps.rancher.io/containers/nodejs:24-dev AS backend-builder
WORKDIR /backend
# cache packages in layer
COPY backend/package.json /backend/package.json
COPY backend/package-lock.json /backend/package-lock.json
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci
# install
COPY backend /backend

FROM dp.apps.rancher.io/containers/nodejs:24

ARG RELEASE_VERSION=latest

LABEL org.opencontainers.image.title="SUSE Application Collection" \
    org.opencontainers.image.description="Integrate the Application Collection into your development lifecycle" \
    org.opencontainers.image.vendor="SUSE LLC" \
    com.docker.desktop.extension.api.version="0.3.4" \
    com.docker.extension.categories="kubernetes,utility-tools" \
    com.docker.desktop.extension.icon="https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/rancher-logo-cow-blue.svg" \
    com.docker.extension.screenshots="[\
        {\"alt\":\"Collection\", \"url\":\"https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/01_collection.png\"}, \
        {\"alt\":\"Application details\", \"url\":\"https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/02_application-details.png\"}, \
        {\"alt\":\"Chart values form\", \"url\":\"https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/03_install-form.png\"}, \
        {\"alt\":\"Workloads\", \"url\":\"https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/04_workloads.png\"}, \
        {\"alt\":\"Workload details\", \"url\":\"https://raw.githubusercontent.com/rancherlabs/application-collection-extension/refs/heads/main/assets/05_workload-details.png\"}\
    ]" \
    com.docker.extension.detailed-description="\
        Build and run cloud-native applications with SUSE's trusted, curated, and continuously updated application collection.\
        <br />\
        This extension helps you integrating the Collection into your local development environment by:\
        <br />\
        <ul>\
            <li>Managing the authentication: docker, helm and kubernetes credentials are automatically configured</li>\
            <li>Making apps plug&play: installs the workloads with a predefined set of values ready for local deployment</li>\
            <li>Helping you stay up-to-date: detects application updates and helps you through the update process</li>\
        </ul>\
        <br />\
        Usage:\
        <br />\
        <ol>\
            <li>Have a target kubernetes cluster configured in your context</li>\
            <li>Install the extension</li>\
            <li><a href=\"https://docs.apps.rancher.io/get-started/authentication/#create-a-personal-access-token\">Generate an access token</a> and configure the authentication</li>\
            <li>Start deploying workloads</li>\
        </ol>\
        " \
    com.docker.extension.publisher-url="https://apps.rancher.io/" \
    com.docker.extension.additional-urls="[\
        {\"title\":\"Product page\",\"url\":\"https://www.suse.com/products/rancher/application-collection\"},\
        {\"title\":\"Web application\",\"url\":\"https://apps.rancher.io\"},\
        {\"title\":\"Documentation\",\"url\":\"https://docs.apps.rancher.io/developer-toolkit/desktop-extension\"},\
        {\"title\":\"Support\",\"url\":\"https://github.com/rancherlabs/application-collection-extension/discussions\"}\
    ]" \
    com.docker.extension.changelog="See full <a href=\"https://github.com/rancherlabs/application-collection-extension/releases/tag/${RELEASE_VERSION}\">change log</a>."

COPY --from=fetcher /tmp/binaries /binaries
COPY --from=fetcher /tmp/binaries/linux /usr/bin
COPY docker-compose.yaml .
COPY metadata.json .
COPY assets/rancher-logo-cow-blue.svg .
COPY --from=client-builder /ui/build ui
COPY --from=backend-builder /backend backend
WORKDIR /backend
ENV PORT=/run/guest-services/application-collection-extension.sock

USER root

CMD ["./bin/www"]
