title: "Bug"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute! Please, fill in this form with as much details as possible.
  - type: input
    attributes:
      label: Title
      description: Brief line with the key terms of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Make sure it as extensive and full of details as possible. This will help you making yourself clear and reachable from the discussions browser.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Extension version running in your environment.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Platform
      options:
        - Rancher Desktop
        - Docker Desktop
        - Both
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Clear steps to reproduce and identify the failure
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If possible, try **attatching** log files, screenshots and/or screen recordings. This will help us significantly to identify and reproduce the problem.
        Make sure you upload them as files, and **do not copy and paste them into the description** to avoid adding visual noise to the thread.