- type: textarea
  attributes:
    label: Description
    description: Make sure it as extensive and full of details as possible. This will help you making yourself clear and reachable from the discussions browser.
  validations:
    required: true
