import { Card, CardContent, Stack, Skeleton, CardActions, Typography, Tooltip, CardActionArea, Chip } from '@mui/material'
import { HelmListItem, WorkloadStatus } from '../../../clients/helm'
import { ChangeCircleOutlined, CheckCircleOutline, DownloadingOutlined, HighlightOffOutlined, HomeOutlined, LanOutlined } from '@mui/icons-material'
import { ArtifactListItemReducedDTO } from '../../../../autogenerated/client/backend'
import { Link } from 'react-router-dom'

export type Workload = HelmListItem & {
  portMappings: {
    targetPort: number,
    nodePort: number,
    protocol: string
  }[],
}

export default function WorkloadCard({ workload, updateVersion, updateBranchVersion }: 
{ workload?: Workload, updateVersion?: ArtifactListItemReducedDTO | null, updateBranchVersion?: ArtifactListItemReducedDTO | null }) {
  
  function StatusIcon({ status }: { status: WorkloadStatus }) {
    switch (status) {
      case WorkloadStatus.Running:
        return <Tooltip title='Running'>
          <CheckCircleOutline color='secondary' />
        </Tooltip>
      case WorkloadStatus.Error:
        return <Tooltip title='Error'>
          <HighlightOffOutlined color='error' />
        </Tooltip>
      case WorkloadStatus.Loading:
        return <Tooltip title='Installing'>
          <DownloadingOutlined />
        </Tooltip>
    }
  }
  
  function WorkloadSkeleton() {
    return (
      <Card variant='outlined'>
        <CardContent sx={ { pb: 1 } }>
          <Stack direction='row' justifyContent='space-between' alignItems='start'>
            <Skeleton width={ 232 } height={ 20 } />
            <Stack direction='row' spacing={ 1 }>
              <Skeleton variant='rectangular' width={ 95 } height={ 24 } />
              <Skeleton variant='rectangular' width={ 65 } height={ 24 } />
            </Stack>
          </Stack>
          <Skeleton width={ 159 } height={ 18 } sx={ { mt: 1 } }/>
          <Skeleton width={ 111 } height={ 18 } />
        </CardContent>
        <CardActions sx={ { justifyContent: 'space-between', px: 2 } }>
          <Skeleton variant='rectangular' width={ 68 } height={ 28 } />
          <Stack direction='row' spacing={ 2 }>
            <Skeleton variant='rectangular' width={ 126 } height={ 28 } />
            <Skeleton variant='rectangular' width={ 65 } height={ 28 } />
          </Stack>
        </CardActions>
      </Card>
    )
  }
  
  if (!workload) return <WorkloadSkeleton />
  
  return (
    <Card
      variant='outlined'
      sx={ { 
        maxWidth: 'lg', 
        '&:hover': { borderColor: 'primary.main', boxShadow: 2 } } }>
      <CardActionArea 
        component={ Link }
        to={ `/workloads/${workload.name}` }>
        <CardContent sx={ { p: 3 } }>
          <Stack direction='row' justifyContent='space-between' alignItems='start'>
            <Stack direction='row' alignItems='center'>
              <Typography variant='h4'>{ workload.name }</Typography>
            </Stack>
            <Stack direction='row' spacing={ 1 }>
              { (updateVersion || updateBranchVersion) && 
                <Tooltip title='Update available'>
                  <ChangeCircleOutlined color='primary' />
                </Tooltip>
              }
              <StatusIcon status={ workload.status } />
            </Stack>
          </Stack>
          <Stack
            direction='row'
            spacing={ 2 }
            sx={ { mt: 1 } }>
            <Tooltip title='Namespace'>
              <Stack 
                direction='row'
                spacing={ 0.75 }
                alignItems='center'>
                <HomeOutlined 
                  fontSize='small' />
                <Typography 
                  color='text.secondary'>
                  { workload.namespace }
                </Typography>
              </Stack>
            </Tooltip>
            { 
              workload.portMappings.map((portMapping, i) => 
                <Tooltip 
                  key={ `${workload.name}-portMapping-${i}` }
                  title='Port mapping'>
                  <Stack 
                    direction='row'
                    spacing={ 0.75 }
                    alignItems='center'>
                    <LanOutlined fontSize='small' />
                    <Typography 
                      color='text.secondary'>
                      { portMapping.nodePort } : { portMapping.targetPort.toString().toUpperCase() } ({ portMapping.protocol })
                    </Typography>
                  </Stack>
                </Tooltip>
              ) 
            }
          </Stack>
        </CardContent>
      </CardActionArea>
    </Card>
  )
}