import { Accordion, AccordionDetails, AccordionSummary, Alert, Button, IconButton, Skeleton, Stack, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useState } from 'react'
import { ArtifactDTO, ArtifactListItemReducedDTO } from '../../../autogenerated/client/backend'
import { installHelmChart } from '../../clients/helm'
import { createDockerDesktopClient } from '@docker/extension-api-client'
import { AddCircleOutline, ContentCopy, ExpandMore, RemoveCircleOutline } from '@mui/icons-material'
import Modal from '../Modal'
import FilePicker from './FilePicker'
import { Notification, useNotificationsCenterOpenDispatch, useNotificationsDispatch } from '../NotificationsCenter/NotificationsContext'
import { v4 as uuid } from 'uuid'
import { checkDocker } from '../../clients/docker'
import { checkKubernetes } from '../../clients/kubectl'

const ddClient = createDockerDesktopClient()

export default function InstallDialog({ branch, artifact, version, open, onSubmit = () => null, onClose = () => null }: 
{ branch: string, artifact: ArtifactListItemReducedDTO | ArtifactDTO, version: string, open: boolean, onSubmit?: () => any, onClose?: () => any }) {
  const [ values, setValues ] = useState<{ key: string, value: string }[]>([])
  const [ currentValue, setCurrentValue ] = useState<{ key?: string, value?: string }>()
  const [ state, setState ] = useState<'loading' | 'ready' | 'installing' | 'error'>()
  const [ error, setError ] = useState<string>()
  
  const notificationsDispatch = useNotificationsDispatch()
  const notificationsCenterOpenDispatch = useNotificationsCenterOpenDispatch()

  useEffect(() => {
    if (open && values.length === 0) {
      setState('loading')
      ddClient.extension.vm?.service?.get(`/charts/${artifact.name.split(':')[0]}/${artifact.version}/local-values`)
        .then(result => {
          const localValues: { key: string, value: string }[] = (result as any).values
          if (localValues.length > 0) {
            setValues(localValues)
          } else {
            setValues([ { key: 'global.imagePullSecrets[0].name', value: 'application-collection' } ])
          }
        })
        .catch(err => {
          console.error('Unexpected error fetching chart local deployment values', err)
          setError('Unexpected error fetching chart local deployment values.')
        })
        .finally(() => setState('ready'))
    }
  }, [open, artifact])

  function install() {
    setState('installing')
    const notification: Notification = {
      id: uuid(),
      title: 'Installing ' + artifact.name,
      description: 'Installation ongoing in the background',
      type: 'progress',
      dismissed: false,
      timestamp: new Date().getTime()
    }

    checkDocker(ddClient)
      .then(() => checkKubernetes(ddClient)
        .then(() => {
          installHelmChart(ddClient, branch, artifact, version, values)
            .then(result => notificationsDispatch({
              type: 'update',
              payload: {
                ...notification,
                title: 'Installed ' + artifact.name,
                description: 'Successfully installed release ' + result.name,
                type: 'success',
                dismissed: false,
                timestamp: new Date().getTime(),
                actionText: 'View details',
                href: `/workloads/${result.name}`
              }
            }))
            .catch((error) => notificationsDispatch({
              type: 'update',
              payload: {
                ...notification,
                title: 'Error installing ' + artifact.name,
                description: error,
                type: 'error',
                dismissed: false,
                timestamp: new Date().getTime()
              }
            }))

          notificationsDispatch({
            type: 'add',
            payload: notification
          })
          setState('ready')
          onSubmit()
          notificationsCenterOpenDispatch(true)
        })
        .catch(e => {
          console.error('Error checking kubernetes existence', e)
          setError('Error with kubernetes, make sure the cluster is up and reachable')
          setState('error')
        }))
      .catch(e => {
        console.error('Error checking docker engine is running', e)
        setError('Error with docker engine, make sure it is running')
        setState('error')
      })
  }

  function LoadingForm() {
    return (
      <>
        <Skeleton height='244px' variant='rectangular' sx={ { mt: 2 } } />
        <Skeleton height='28px' width='300px' variant='rectangular' sx={ { mt: 2 } } />
        <Skeleton height='68px' variant='rectangular'sx={ { mt: 2 } } />
        <Stack direction='row' alignItems='space-between' sx={ { mt: 2 } }>
          <Skeleton height='33px' width='78px' variant='rectangular' sx={ { mt: 1 } } />
          <Skeleton height='33px' width='78px' variant='rectangular' sx={ { mt: 1 } } />
        </Stack>
      </>
    )
  }

  if (state === 'loading') {
    return (
      <Modal
        title='Configure installation'
        subtitle='Set Helm Chart values manually or through a YAML file'
        open={ open }
        onClose={ onClose }>
        <LoadingForm />
      </Modal>
    )
  }

  return (
    <Modal
      title='Configure installation'
      subtitle='Set Helm Chart values manually or through a YAML file'
      open={ open }
      onClose={ onClose }
      onSubmit={ install }>
      {
        state === 'error' && 
        <Alert severity='error' icon={ false } sx={ { mt: 2 } }>
          <Typography>{ error }</Typography>
        </Alert>
      }
      { 
        values.map((v, i) => 
          <Stack key={ `value-${i}` } direction='row' alignItems='center' spacing={ 2 } sx={ { mt: 2 } }>
            <TextField 
              onChange={ (e) => setValues(values.map((v, j) => i == j ? { key: e.target.value, value: v.value } : v)) }
              value={ v.key }
              size='small'
              sx={ { flexGrow: 1 } } />
            <TextField 
              onChange={ (e) => setValues(values.map((v, j) => i == j ? { key: v.key, value: e.target.value } : v)) }
              value={ v.value }
              size='small'
              sx={ { flexGrow: 1 } } />
            <IconButton onClick={ () => setValues(values.filter((v, j) => j !== i)) }>
              <RemoveCircleOutline />
            </IconButton>
          </Stack>) 
      }
      <Stack 
        direction='row' 
        alignItems='center' 
        spacing={ 2 }
        sx={ { my: 2 } }>
        <TextField 
          placeholder='Key'
          value={ currentValue?.key || '' }
          size='small'
          onChange={ (e) => setCurrentValue({ ...currentValue, key: e.target.value }) }
          sx={ { flexGrow: 1 } } />
        <TextField 
          placeholder='Value'
          value={ currentValue?.value || '' }
          size='small'
          onChange={ (e) => setCurrentValue({ ...currentValue, value: e.target.value }) }
          sx={ { flexGrow: 1 } } />
        <IconButton onClick={ () => {
          if (currentValue?.key && currentValue.value) setValues([ ...values, (currentValue as { key: string, value: string }) ]) 
          setCurrentValue({})
        } }>
          <AddCircleOutline />
        </IconButton>
      </Stack>
      <Stack direction='row' alignItems='center' flexWrap='wrap' rowGap={ 2 } sx={ { overflowX: 'hidden', pt: '1px' } }>
        <FilePicker onSelect={ newValues => setValues([...values, ...newValues]) } />
      </Stack>
      <Accordion sx={ { mt: 2, boxShadow: 'none', '::before': { content: 'unset' } } }>
        <AccordionSummary expandIcon={ <ExpandMore /> } sx={ { p: 0, m: 0 } }>
          <Stack>
            <Typography variant='h4'>Need help?</Typography>
            <Typography variant='h5'>Run this command to get the chart's values</Typography>
          </Stack>
        </AccordionSummary>
        <AccordionDetails>
          <Stack direction='row' alignItems='center' justifyContent='space-between' sx={ { background: 'rgba(0, 0, 0, 0.1)', p: 1 } }>
            <Typography variant='code'>helm show values oci://dp.apps.rancher.io/charts/{ artifact.name.split(':')[0] } --version { artifact.version }</Typography>
            <Tooltip title='Copy'>
              <IconButton onClick={ () => navigator.clipboard.writeText(`helm show values oci://dp.apps.rancher.io/charts/${ artifact.name.split(':')[0] } --version ${ artifact.version }`) } size='small'>
                <ContentCopy />
              </IconButton>
            </Tooltip>
          </Stack>
        </AccordionDetails>
      </Accordion>
      <Stack direction='row' justifyContent='space-between' sx={ { mt: 2 } }>
        <Button 
          color='inherit'
          onClick={ onClose }
          disabled={ state === 'installing' }>Cancel</Button>
        {
          state === 'installing' ?
            <Button 
              type='submit'
              variant='contained'
              color='inherit'
              disabled>Installing...</Button>
            :
            <Button 
              type='submit'
              variant='contained'>Install</Button>
        }
      </Stack>
    </Modal>
  )
}
