import { Stack, Typography } from '@mui/material'
import { useEffect, useState } from 'react'
import { ApplicationDTOPackagingFormatEnum, ApplicationReducedViewDTO } from '../../../autogenerated/client/backend'
import { applicationsClient } from '../../clients/backend'
import ApplicationCard, { ApplicationCardSkeleton } from './components/ApplicationCard'
import { useAuth, useAuthDispatch } from '../../AuthContext'
import { InfiniteScroll } from './components/InfiniteScroll'
import { AxiosError } from 'axios'

export default function ApplicationsPage() {
  const [ applications, setApplications ] = useState<ApplicationReducedViewDTO[]>([])
  const [ nextPage, setNextPage ] = useState(1)
  const [ totalSize, setTotalSize ] = useState(0)
  const auth = useAuth()
  const dispatch = useAuthDispatch()

  useEffect(() => {
    if (auth?.auth) {
      applicationsClient(auth?.auth).getApplications(undefined, undefined, ApplicationDTOPackagingFormatEnum.HelmChart)
        .then(response => {
          if (response.status == 200) {
            setApplications(response.data.items)
            setNextPage(response.data.page === response.data.total_pages ? response.data.page || 0 : nextPage + 1)
            setTotalSize(response.data.total_size || 0)
          }
        })
        .catch(e => {
          console.error(`Unexpected error fetching applications [error=${e}]`)
          if (e instanceof AxiosError && e.status == 401) dispatch({ type: 'delete' })
        })
    }
  }, [auth])

  function loadAppsPage() {
    if (auth?.auth) {
      applicationsClient(auth?.auth).getApplications(undefined, undefined, ApplicationDTOPackagingFormatEnum.HelmChart, undefined, nextPage)
        .then((response) => {
          setApplications([...applications, ...response.data.items])
          setNextPage(response.data.page === response.data.total_pages ? response.data.page || 0 : nextPage + 1)
        })
        .catch(e => {
          console.error(`Unexpected error fetching applications [error=${e}]`)
          if (e instanceof AxiosError && e.status == 401) dispatch({ type: 'delete' })
        })
    }
  }

  return (
    <>
      <Typography variant='h2'>Applications</Typography>
      <Typography variant='h5' gutterBottom>Select an application to install</Typography>
      {  
        applications.length > 0 ? 
          <InfiniteScroll
            load={ loadAppsPage } 
            hasMore={ applications.length < totalSize  } 
            loader={ <ApplicationCardSkeleton /> } 
            style={ { width: '100%' } }>
            <Stack rowGap={ 3 } flexGrow={ 1 } sx={ { mt: 2, mb: 3 } }>
              { applications.map(a => <ApplicationCard app={ a } key={ a.slug_name } />) }
            </Stack>
          </InfiniteScroll> :
          <Stack rowGap={ 3 } flexGrow={ 1 } sx={ { mt: 2 } }>
            { Array.apply(null, Array(20)).map((v, i) => <ApplicationCardSkeleton key={ `placeholder-app-${i}` } />) }
          </Stack>
      }
    </>
  )
}