import { Chip, Skeleton, Stack, Typography } from '@mui/material'
import { useAuth } from '../../AuthContext'
import { ApplicationDTO, ApplicationDTOPackagingFormatEnum, ComponentDTO } from '../../../autogenerated/client/backend'
import { ReactElement, useEffect, useState } from 'react'
import { applicationsClient, componentsClient } from '../../clients/backend'
import { Link, useLoaderData } from 'react-router-dom'
import BranchesTable from './components/BranchesTable'
import { AxiosError } from 'axios'

export async function loader({ params }: { params: any }): Promise<string> {
  return params.slugName
}

export default function ApplicationDetailsPage() {
  const [ application, setApplication ] = useState<ApplicationDTO>()
  const [ component, setComponent ] = useState<ComponentDTO>()
  const [ error, setError ] = useState<ReactElement>()

  const auth = useAuth()
  const slugName = useLoaderData()

  useEffect(() => {
    if (auth) {
      applicationsClient(auth).getApplication(slugName as string)
        .then(response => {
          if (response.status == 200) {
            setApplication(response.data)
          }
        }).catch(e => {
          console.error(`Unexpected error fetching application [slugName=${slugName}]`, e)
          let content: ReactElement
          if (e instanceof AxiosError && e.status == 401) {
            content = <>Authentication failed. Go to the <Link to='/settings'>Settings page</Link> to manage the access token.</>
          } else {
            content = <>There was an unexpected error loading the application. Try again in a couple of minutes.</>
          }
          setError(content)
        })
      componentsClient(auth).getComponent(slugName as string)
        .then(response => {
          if (response.status == 200) {
            setComponent(response.data)
          }
        }).catch(e => {
          console.error(`Unexpected error fetching component [slugName=${slugName}]`, e)
          let content: ReactElement
          if (e instanceof AxiosError && e.status == 401) {
            content = <>Authentication failed. Go to the <Link to='/settings'>Settings page</Link> to manage the access token.</>
          } else {
            content = <>There was an unexpected error loading the application. Try again in a couple of minutes.</>
          }
          setError(content)
        })
    }
  }, [])

  if (error) {
    return <Typography color='error' sx={ { mt: 2 } }>{ error }</Typography>
  }

  if (!application || !component) {
    return (
      <>
        <Stack direction='row' spacing={ 2 } alignItems='center'>
          <Skeleton variant='circular' height={ 60 } width={ 60 } />
          <Stack direction='column' alignItems='start' spacing={ 1 }>
            <Skeleton variant='text' height={ 25 } width={ 150 } />
            <Skeleton variant='rectangular' height={ 24 } width={ 74 } />
          </Stack>
        </Stack>
        <Skeleton variant='text' width='100%' sx={ { mt: 2 } } />
        <Skeleton variant='text' width='100%' />
        <Skeleton variant='text' width='50%' sx={ { mb: 2.5 } } />
        <Typography variant='h3'>Manage versions</Typography>
        <Typography variant='h5' sx={ { mb: 3 } }>Install, pause, stop and update workloads</Typography>
        <Skeleton variant='rectangular' height={ 100 } width='100%' />
      </>
    )
  }

  function humanFriendlyPackagingFormat(packagingFormat?: ApplicationDTOPackagingFormatEnum) {
    if (packagingFormat === ApplicationDTOPackagingFormatEnum.HelmChart) return 'Helm chart'
    if (packagingFormat === ApplicationDTOPackagingFormatEnum.Container) return 'Single container'
    return 'Coming soon'
  }

  return (
    <>
      <Stack direction='row' spacing={ 2 } alignItems='center'>
        { application.logo_url && <img src={ `https://apps.rancher.io${application.logo_url}` } alt={ `${application.name} logo` } height={ 60 } width={ 60 } style={ { height: '100%' } } /> }
        <Stack direction='column' alignItems='start' spacing={ 1 }>
          <Typography variant='h2'>{ application.name }</Typography>
          <Chip label={ humanFriendlyPackagingFormat(application.packaging_format) } size='small' color='primary' />
        </Stack>
      </Stack>
      <Typography sx={ { my: 2 } }>{ application.description }</Typography>
      <Typography variant='h3'>Manage branches</Typography>
      <Typography variant='h5' sx={ { mb: 3 } }>Install, pause, stop and update workloads</Typography>
      <BranchesTable branches={ component.branches } packagingFormat={ application.packaging_format } />
    </>
  )
}