name: Signed commits tests

on:
  push:
    branches:
      - gh-app-tests

jobs:
  commit:
    name: Commit
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Load app secrets from vault
      uses: rancher-eio/read-vault-secrets@main
      id: load-token
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/github/app-credentials appId | APP_ID;
          secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATE_KEY

    - name: Generate GH token from GH App secrets
      id: create-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ github.event.repository.name }}

    - name: Configure Git
      shell: sh
      run: |
        git config --global safe.directory $(pwd)
        git config --global user.name "Application Collection Bot"
        git config --global user.email "application-collection-bot@users.noreply.github.com"

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
      env:
        GPG_PRIVATE_KEY: ${{ env.PRIVATE_KEY }}

    - name: Generate empty commit
      id: generate-images
      env:
        GH_TOKEN: ${{ steps.create-token.outputs.token }}
      run: |
        gh auth setup-git
        git commit --allow-empty -m "Signed commit test"
        git push origin gh-app-tests
